#!/bin/bash
# Example usage of hybrid enrichment script

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     Hybrid Product Enrichment - Example Usage                 ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Example 1: Dry run on small sample
echo "Example 1: Dry run on 50 products"
echo "Command: tsx scripts/enrich-products-hybrid.ts --limit 50"
echo ""
echo "This will:"
echo "  - Process 50 products"
echo "  - Show what would be enriched"
echo "  - Not save to database"
echo "  - Estimate costs"
echo ""
read -p "Press Enter to continue..."
echo ""

# Example 2: Heuristic only (zero cost)
echo "Example 2: Heuristic enrichment only (zero cost)"
echo "Command: tsx scripts/enrich-products-hybrid.ts --skip-llm --live --limit 1000"
echo ""
echo "This will:"
echo "  - Use only keyword matching"
echo "  - Process up to 1000 products/second"
echo "  - Zero LLM costs"
echo "  - Save to database"
echo ""
read -p "Press Enter to continue..."
echo ""

# Example 3: Full hybrid enrichment
echo "Example 3: Full hybrid enrichment with LLM gap-fill"
echo "Command: tsx scripts/enrich-products-hybrid.ts --live --batch-size 15 --concurrency 3"
echo ""
echo "This will:"
echo "  - Run heuristic pass first (fast, free)"
echo "  - Run LLM gap-fill on under-enriched products"
echo "  - Batch 15 products per LLM call"
echo "  - Run 3 batches in parallel"
echo "  - Estimated cost: ~$1-2 per 10,000 products"
echo ""
read -p "Press Enter to continue..."
echo ""

# Example 4: Resume interrupted run
echo "Example 4: Resume interrupted enrichment"
echo "Command: tsx scripts/enrich-products-hybrid.ts --resume --live"
echo ""
echo "This will:"
echo "  - Load checkpoint from previous run"
echo "  - Skip already processed products"
echo "  - Continue from where it left off"
echo ""
read -p "Press Enter to continue..."
echo ""

# Example 5: Maximum speed
echo "Example 5: Maximum speed (heuristic only, no LLM)"
echo "Command: tsx scripts/enrich-products-hybrid.ts --skip-llm --live"
echo ""
echo "This will:"
echo "  - Process all products with heuristics only"
echo "  - ~1000+ products/second"
echo "  - Zero cost"
echo "  - Best for initial enrichment"
echo ""
read -p "Press Enter to continue..."
echo ""

# Example 6: Maximum accuracy
echo "Example 6: Maximum accuracy (LLM only, no heuristics)"
echo "Command: tsx scripts/enrich-products-hybrid.ts --skip-heuristic --live --batch-size 10"
echo ""
echo "This will:"
echo "  - Skip heuristic pass"
echo "  - Use only LLM enrichment"
echo "  - Smaller batches for better accuracy"
echo "  - Higher cost but best quality"
echo ""
read -p "Press Enter to continue..."
echo ""

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     Example Usage Complete                                     ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Recommended workflow:"
echo "  1. tsx scripts/enrich-products-hybrid.ts --limit 100  # Test"
echo "  2. tsx scripts/enrich-products-hybrid.ts --live       # Full run"
echo ""
echo "For more information, see: docs/runbooks/hybrid-enrichment.md"
echo ""
